### ISSUE TITLE
How should we handle vote executions that revert?

### ISSUE THREAD

**Issue by willjgriff** [1Hive/dandelion-voting-app#27]
Vote's can be prevented from being executed for reasons outside the control of the DAO eg the contract being called is no longer in a state that will allow the transaction to pass once the vote is over. We currently prevent a vote from being executed if the previous vote hasn't been executed, which in this case will prevent future passing votes from being executed until a failed vote is created and it's duration passed. 

Potential solutions:
1) Remove the restriction which forces votes to be executed in order of creation but require that the last accepted votes execution time + some period (perhaps 1/2 buffer) has passed before execution is possible. Can attempt execution infinite times.
2) Keep the restriction but only allow vote execution to be attempted once. If it fails that vote can never be executed. Requires some hacky code involving a `public`/`external` function that can only be called internally using `address(this).call()`.
3) Keep the restriction and allow a specified number of execution attempts, separated by some amount of time. Also requires hacky code from 2. This introduces questions about when someone can exit and when a subsequent vote can be executed, after the first failed attempt or a later attempt? Also what do we specify as the number of execution attempts and how much are they separated by? 

From these, it feels like the trade off is between solution 1) forcing execution order with a single execution attempt and solution 2) encouraging execution order (by restricting execution until the previous votes execution time has passed plus some) with infinite execution attempts. Solution 3 seems a bit complex, but it's possible.

**Comment by lkngtn** [comment]
> Remove the restriction which forces votes to be executed in order of creation but require that the last accepted votes execution time + some period (perhaps 1/2 buffer) has passed before execution is possible. Can attempt execution infinite times.

Won't it always be the case that the next available vote won't be available to be executed until after the full buffer has passed? 

I don't see a significant downside to this approach in terms of vote execution. 

In terms of users being able to "exit" using the acl oracle. It should be possible to exit after 1/2 the buffer duration has passed even if the vote has not been executed. The 1/2 period is intended to ensure users are both locked in for votes they voted yes on, but still have an opportunity to exit before the next vote that they didn't vote yes on gets executed. 

The idea here is that, the 1/2 buffer duration give other members an opportunity to execute the vote before anyone who voted yes on the proposal has the opportunity to exit. 

If we are extra paranoid, it may be possible for an attacker to get around this by passing a proposal that will fail to execute until after 1/2 the buffer duration, but will be able to execute after the duration. In this case for safety it may make sense to allow a vote to be dismissed if some condition is met. We could say that if the current token supply the vote is based on is x% of the supply at the block the proposal started the vote can be dismissed rather than executed.

**Comment by fabriziovigevani** [comment]
> Won't it always be the case that the next available vote won't be available to be executed until after the full buffer has passed?

So if i understand correctly, we are already kind of enforcing execution order with the (buffer / 2) delay because if a current vote is available to be executed, it means that prior vote's (buffer /2) delay has already passed, meaning that  it's not necessary to check if they were executed as the members could have already make an exit right?   

> If we are extra paranoid, it may be possible for an attacker to get around this by passing a proposal that will fail to execute until after 1/2 the buffer duration, but will be able to execute after the duration

Could you extend on this a little bit more?

**Comment by willjgriff** [comment]
> Won't it always be the case that the next available vote won't be available to be executed until after the full buffer has passed?
>
>I don't see a significant downside to this approach in terms of vote execution.

Yep, good point, my suggestion doesn't take that into account. If that sounds acceptable then that's great for me.

> We could say that if the current token supply the vote is based on is x% of the supply at the block the proposal started the vote can be dismissed rather than executed.

Sounds reasonable, I could investigate adding this if you feel it's worth having although I think a single individual having that much control over an external protocol/contract is unlikely.

**Comment by lkngtn** [comment]
> Sounds reasonable, I could investigate adding this if you feel it's worth having although I think a single individual having that much control over an external protocol/contract is unlikely.

My suggestion would be to create an issue to track it but we can keep it in the backlog for now. Based on user feedback and other priorities we can decide whether it makes sense to implement in the future, I don't think it needs to be included in the initial released version.

**Comment by bingen** [comment]
> Won't it always be the case that the next available vote won't be available to be executed until after the full buffer has passed?

I don't fully get this, sorry. The buffer is applied to vote start block, right? So that means that the next available won't be available to be executed until after the full buffer (plus the duration of the vote) has passed *from the beginning* of the previous vote, but that could be before the previous vote has been executed, right? So I guess there should be a temporal check after the execution block.

Also, could it happen that the execution delay is shortened in between votes (that'd be hard if the role is assigned to the voting app itself) and the order is actually reversed?
```
   duration        e.d.
+-------------+----------+        -> vote 1
  b    duration      e.d.
+---+-------------+-----+         -> vote 2
```

**Comment by lkngtn** [comment]
> I don't fully get this, sorry. The buffer is applied to vote start block, right? So that means that the next available won't be available to be executed until after the full buffer (plus the duration of the vote) has passed from the beginning of the previous vote, but that could be before the previous vote has been executed, right? 

Yes it should work as you describe. The buffer ensures that the votes do not start at the same time, assuming vote duration and delay are constant, then there should always be the same buffer between each event (start, execution). The assumption we are making is that there will be a reasonable opportunity for someone in the org to execute the vote before people who voted yes on it have the opportunity to exit. 

> Also, could it happen that the execution delay is shortened in between votes (that'd be hard if the role is assigned to the voting app itself) and the order is actually reversed?

Yes if the delay, or vote duration are adjusted, it can temporarily mess up our ordering assumption. I don't think it make sense to try and design around that edge case though, if there is concerns over that changing the duration they should not vote to change the duration (or even discard this permission), or they should should exit in response to it being changed.

**Comment by lkngtn** [comment]
> If we are extra paranoid, it may be possible for an attacker to get around this by passing a proposal that will fail to execute until after 1/2 the buffer duration, but will be able to execute after the duration

> Could you extend on this a little bit more? 

What I mean is that someone could create a contract that will revert conditionally. Create a proposal to send some of the org's funds to that contract, then assuming they have enough shares to approve the proposal, vote in favor of the proposal. The revert will prevent it from being executed until the proposer is able to exit. After they have exited, their malicious contract may no longer revote allowing the vote to be executed. 

This is a fairly outlandish scenario, and it should be pretty obvious to everyone that it is happening and so everyone should exit. They can create a new org and not let the malicious person back in. It's more a hypothetical to help better understand the limitations of our approach than one that I think is important for us to address.

**Comment by bingen** [comment]
I'm thinking that an option to avoid the hacky solution would be to implement a new Executor, essentially a copy of [this one](https://github.com/aragon/aragonOS/blob/next/contracts/evmscript/executors/CallsScript.sol) but removing the reverts (and you could contribute it back to aragonOS :wink:).
With that I would go for 1 execution per vote. If the execution failed, a new vote (probably referencing the old one, explaining why it failed and why it needs to be voted again) could be created.

**Comment by willjgriff** [comment]
> I'm thinking that an option to avoid the hacky solution would be to implement a new Executor, essentially a copy of [this one](https://github.com/aragon/aragonOS/blob/next/contracts/evmscript/executors/CallsScript.sol) but removing the reverts (and you could contribute it back to aragonOS 😉).

I would love to write a new executor and understand properly how all that stuff works. However, it sounds like we can do without for now, maybe another time.

**Comment by bingen** [comment]
> I would love to write a new executor and understand properly how all that stuff works. However, it sounds like we can do without for now, maybe another time.

Sounds good. If you need help just let me know.

**Comment by bingen** [comment]
> The assumption we are making is that there will be a reasonable opportunity for someone in the org to execute the vote before people who voted yes on it have the opportunity to exit.

So, to help me understand the requirements, what we want is that:
- Holders who voted Yes on last vote are not able to exit if that vote is still pending or not executed.
- Holders who voted No or didn't vote on last vote are able to exit before it is executed (that's what `executionDelayBlocks` is for, right?)
- A vote that passed but can not be executed (for external reasons, like the script reverting), doesn't block execution of subsequent votes.
Are these correct? Am I missing something?
I think I would insist on forcing buffer buffer to be always greater than vote duration + execution delay. That would make the org less agile but safer. I think I have missed some discussions but otherwise I see the following attack vector by creating a new vote right away to be able to exit. Let's assume vote 1 is malicious. During the execution delay period, last vote is number 2, the one that Oracle will check, so an attacker that voted yes on 1 can exit as long as votes no or doesn't vote on 2.
```
   duration        e.d.
+-------------+----------+        -> vote 1
  b    duration      e.d.
+---+-------------+----------+         -> vote 2
     -> from here on attacker can exit
```

**Comment by willjgriff** [comment]
> * During the execution delay period, last vote is number 2, the one that Oracle will check, so an attacker that voted yes on 1 can exit as long as votes no or doesn't vote on 2.

This is my mistake, apologies. I originally programmed it so that the latest vote is the one used when determining if someone can exit (/`canPerform()` will return true for). However, I should have used the last vote that the sender voted yes on. Which I have changed in this PR: https://github.com/1Hive/dandelion-voting-app/pull/28

Sorry again, this was my mistake.
